services:
  db:
    image: postgres:18
    container_name: budget_management
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - '${DB_PORT}:5432'

volumes:
  pgdata:
