export enum OrganizationPermission {
  MEMBERS_VIEW = 'members_view',
  MEMBERS_MANAGE = 'members_manage',
  TRANSACTION_ENTITIES_VIEW = 'transaction_entities_view',
  TRANSACTION_ENTITIES_MANAGE_OWN = 'transaction_entities_manage_own',
  TRANSACTION_ENTITIES_MANAGE_ALL = 'transaction_entities_manage_all',
  TRANSACTIONS_VIEW_OWN = 'transactions_view_own',
  TRANSACTIONS_VIEW_ALL = 'transactions_view_all',
  TRANSACTIONS_MANAGE_OWN = 'transactions_manage_own',
  TRANSACTIONS_MANAGE_ALL = 'transactions_manage_all',
  ESTIMATIONS_VIEW_OWN = 'estimations_view_own',
  ESTIMATIONS_VIEW_ALL = 'estimations_view_all',
  ESTIMATIONS_MANAGE_OWN = 'estimations_manage_own',
  ESTIMATIONS_MANAGE_ALL = 'estimations_manage_all',
  ORGANIZATION_MANAGE = 'organization_manage',
  ANALYTICS_VIEW_OWN = 'analytics_view_own',
  ANALYTICS_VIEW_ALL = 'analytics_view_all',
}
