export enum TransactionEntityType {
  EMPLOYER = 'employer',
  CLIENT = 'client',
  RETAILER = 'retailer',
  FOOD_SERVICE = 'food_service',
  HOUSING = 'housing',
  UTILITY = 'utility',
  TRANSPORT = 'transport',
  ACCOMMODATION = 'accommodation',
  HEALTHCARE = 'healthcare',
  EDUCATION = 'education',
  ENTERTAINMENT = 'entertainment',
  PROFESSIONAL_SERVICE = 'professional_service',
  FINANCIAL_INSTITUTION = 'financial_institution',
  GOVERNMENT = 'government',
  PERSON = 'person',
  CHARITY = 'charity',
  OTHER = 'other',
}
